### ISSUE TITLE
tabbed formatting is currently inconsistent

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/touchbase#1]
I noticed you're using tabs instead of spaces.  Currently, that's leading to pretty jagged rows of code as you can see here:
![image](https://cloud.githubusercontent.com/assets/81302/9618754/1ce51d5e-50be-11e5-8930-8bc70bffcc62.png)

Generally I prefer spaces instead of tabs, but it's up to you.  If you're using tabs, it'd be good to line up the columns correctly.

**Comment by pranavmayuram** [comment]
Should be resolved in the latest commit. Please tell me if the change has worked for you. One API has also been updated, so pull for the new changes.
