### ISSUE TITLE
Feature request: add screenshots to the README

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/touchbase#2]
If I saw some screenshots, I'd be more enticed to go through the trouble of trying to get this working.

**Comment by pranavmayuram** [comment]
Will do, appreciate the suggestion. Please tell me if the setup goes smoothly for you.

**Comment by pranavmayuram** [comment]
Would it be appropriate to have screenshots in a separate markdown file? Alternatively, the user could be referred to this new '.md' file, or they could be referred to the files with screenshots in the 'Documentation folder'. I'm not sure if either of these would be acceptable, but I'm not sure where the screenshots would have a place in the README either.

**Comment by tleyden** [comment]
Here's an example README that has screenshots:

https://github.com/couchbaselabs/ToDoLite-iOS

**Comment by pranavmayuram** [comment]
Will do, appreciate the example.

**Comment by pranavmayuram** [comment]
Tell me if the new update looks sufficient.

**Comment by tleyden** [comment]
Looks great!
